services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./mariadb_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./frontend/openCTF
      dockerfile: Dockerfile
    ports:
      - 80:80

volumes:
  mariadb_data: